### ISSUE TITLE
Getting Diff from Last Commit Only Not Commit Lists from Push Command

### ISSUE THREAD

**Issue by dev-whoan** [emmeowzing/dynamic-continuation-orb#101]
## What happened:

- Only last commit is calculated for getting diff, make modules_filtered and reducing the yamls for continue pipelines when Push commits

## Expected behavior:

- All the commits are calculated to filter and reduce the configurations

## Additional Information:
- Let's assume there are 2 applications in monorepo, and it followed the `.circleci` structure to use this orb

- So the `.circleci` directory has
```
.cirlceci/
  apps.foo.yml
  apps.bar.yml
```

- And each directories as follows:
```
apps/
  foo/
    hello_world
  bar/
    bye_world
```

### So what is the problem
- I created `test`file in each directories, and commit those things in seperatedly.
```
apps/
  foo/
    hello_world
    test                          # Newely created
  bar/
    bye_world
    test                          # Newely created
```

- So the commits:
```git
$ git add apps/foo/test
$ git commit "Add test in apps.foo"

$ git add apps/bar/test
$ git commit "Add test in apps.bar"

$ git push origin main
```

- After pushing those commits to my git repository, I expected runnig workflows as follows
  1. setup
  2. apps.foo.yml
  3. apps.bar.yml
- But actually, only last commit will be calculated, so following workflows will be executed
  1. setup
  2. apps.bar.yml

- I tested it as adding the changes in single commit, and pushed. Then the workflows are executed as I expected.

### So my suggestion is
- Could you update your orb to calculate for filtering modules to all the commits from the last update?

**Comment by emmeowzing** [comment]
May I ask if you're pushing directly to the project's default branch? E.g. main or master? If that's the case, then by default, the orb only compares the latest commit on the default branch to the penultimate commit. This is the intended behavior.

On the other hand, if you're observing this behavior in a PR, it's the sign of a bug. In this case, the intended behavior is that your branch is compared as a whole against the project's default branch. In this case, the cumulative change is addressed by running corresponding pipelines.

**Comment by emmeowzing** [comment]
> May I ask if you're pushing directly to the project's default branch? E.g. main or master? If that's the case, then by default, the orb only compares the latest commit on the default branch to the penultimate commit. This is the intended behavior.
> 
> On the other hand, if you're observing this behavior in a PR, it's the sign of a bug. In this case, the intended behavior is that your branch is compared as a whole against the project's default branch. In this case, the cumulative change is addressed by running corresponding pipelines.

Ah, I just noticed you're pushing to main. Yeah, this is intended behavior. Reason being that, there's no way to determine exactly how many commits an author wishes to include as far as triggering workflows. I would recommend creating a new branch off main so changes are additive. Then, when you (squash) merge back, all your changes are compressed to a single commit on main.

**Comment by dev-whoan** [comment]
Thank you. I understand :))
