### ISSUE TITLE
Recursively evaluate environment variables for all SH_*-prefixed environment variables

### ISSUE THREAD

**Issue by emmeowzing** [emmeowzing/dynamic-continuation-orb#41]
https://github.com/bjd2385/dynamic-continuation-orb/blob/14ea5b11c1e875f5fb1db40a4da22c5132bc5a7a/src/scripts/filter.sh#L8

I _think_ all environment variables prefixed with `SH_*` should be recursively `eval echo`'ed, such as in this example. Maybe future-proofing.

**Comment by bjd2385** [comment]
https://discuss.circleci.com/t/new-cli-command-circleci-env-subst/47699 - this command is definitely relevant
