### ISSUE TITLE
[Feature Request] implement common config for lib jobs and commands

### ISSUE THREAD

**Issue by emmeowzing** [emmeowzing/dynamic-continuation-orb#97]
If we have a scenario where we have several similar submodules or packages that require the same job definition (that can't be imported in an orb - that's a lot of work, e.g.), it should be possible to specify a file that's a library of commands and jobs that isn't checked by itself, but is merged with the other configs. This gives us a centralized location to stash reused jobs and allows the user to cut down on code duplication.

**Comment by sylvain-blot-sp** [comment]
If anyone needs a quick workaround:

```
      - dynamic/continue:
          base-revision: main
          pre-script: yq --inplace '.jobs *= (load(".circleci/config.yml").jobs) | .' .circleci/YOUR_MODULE.yml && yq --inplace '.orbs *= (load(".circleci/YOUR_MODULE.yml").orbs) | .' .circleci/YOUR_MODULE.yml.yml
```

**Comment by emmeowzing** [comment]
Thanks @sylvain-blot-sp , I'll cut a release in the next few days that encompasses this change.
